import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Input from "~/components/input"
import { useState } from "react";

export default function Home() {
  const post = api.postapi.postsample.useMutation();
  const[inputs,setInputs]=useState({
    name:"",
    email:"",
    age:"",
  });
  const getinputdata=(event:React.ChangeEvent<HTMLInputElement>)=>{
    let{name,value}=event.target;
    let u ={[name]:value};
    setInputs((prev)=>({...prev, ...u}));
    
   
  };

  const sendinput=()=>{
    console.log(inputs);
    post.mutate(inputs);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Input type="text" name="name" placeholder="Enter Your Name" onChange={getinputdata}/>
        <Input type="email" name="email" placeholder="Enter Your Email" onChange={getinputdata}/>
        <Input type="text" name="age" placeholder="Enter Your Age" onChange={getinputdata}/>

        <button onClick={sendinput} className="btn btn-primary">Add Data</button>
      </main>
    </>
  );
}
